version: "3.9"
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: desafio_development
      POSTGRES_PASSWORD: desafiopass
    volumes:
      - /private/docker/volumes/postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    tty: true
    stdin_open: true
    env_file:
      - .env
    container_name: web
    volumes:
      - ./:/src
    ports:
      - "3000:3000"